version: "3.7"

services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: client
    command: npm start
    ports:
      - '5000:5000'
      
  api_mongo:
    image: mongo:latest
    container_name: api_mongo
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
    container_name: server
    command: npm start && npm run seed
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      - "8080:8080"    
      - "9222:9229"

volumes:
  mongodb_api:
