FROM node:14.14.0

WORKDIR /usr/app

COPY package*.json ./

RUN npm install typescript -g

RUN npm install tsc-watch -g

RUN npm install -g glob

RUN npm install --save glob

RUN npm install

COPY . .